# --- POCZĄTEK PLIKU GENERATOR ---
# Wersja v1.00 - Inicjalizacja konfiguracji generatora i portu AUX dla Hackman Flex3L.
# Plik zawiera sensory produkcji, napięć, mocy oraz ustawienia trybu pracy portu (Generator/SmartLoad/Microinverter).

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Daily Generator Production"
    id: hackman_flex3l_daily_generator_production
    register_type: holding
    address: 636
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:generator-portable"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Total Generator Production"
    id: hackman_flex3l_total_generator_production
    register_type: holding
    address: 637
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L1 Voltage"
    id: hackman_flex3l_generator_l1_voltage
    register_type: holding
    address: 761
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L2 Voltage"
    id: hackman_flex3l_generator_l2_voltage
    register_type: holding
    address: 762
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L3 Voltage"
    id: hackman_flex3l_generator_l3_voltage
    register_type: holding
    address: 763
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L1 Power"
    register_type: holding
    address: 764
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L2 Power"
    register_type: holding
    address: 765
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator L3 Power"
    register_type: holding
    address: 766
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Power Total"
    id: hackman_flex3l_generator_power_total
    register_type: holding
    address: 767
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L AC Generator Relay" # bit 3
    register_type: holding
    address: 652
    bitmask: 0x8
    device_class: power
    icon: "mdi:generator-stationary"

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Port Use"
    address: 233
    value_type: U_WORD
    entity_category: config
    icon: "mdi:connection"
    optionsmap:
      "Generator Input": 0
      "SmartLoad Output": 1
      "Micro Inverter Input": 2

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator"
    register_type: holding
    address: 232
    bitmask: 1
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Microinverter Export Cut-off"
    register_type: holding
    address: 278
    bitmask: 0x0001 # bit 0
    entity_category: config
    icon: "mdi:solar-panel"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Peak Shaving Enable"
    register_type: holding
    address: 278
    bitmask: 0x0004 # bit 2
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator On-Grid Always On"
    register_type: holding
    address: 278
    bitmask: 0x0040 # bit 6
    entity_category: config
    icon: "mdi:generator-stationary"

number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L SmartLoad Off Voltage"
    id: hackman_flex3l_smartload_off_voltage
    address: 234
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    mode: box
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L SmartLoad Off SOC"
    address: 235
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    mode: box
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L SmartLoad On Voltage"
    id: hackman_flex3l_smartload_on_voltage
    address: 236
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    mode: box
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L SmartLoad On SOC"
    address: 237
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    mode: box
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Operating Time"
    address: 221
    unit_of_measurement: "h"
    device_class: duration
    value_type: U_WORD
    multiply: 10
    min_value: 0
    max_value: 24
    step: 1
    entity_category: config
    mode: box
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Cooling Time"
    address: 222
    unit_of_measurement: "h"
    device_class: duration
    value_type: U_WORD
    multiply: 10
    min_value: 0
    max_value: 24
    step: 1
    entity_category: config
    mode: box
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L PV Minimum Power To Start Generator"
    address: 239
    unit_of_measurement: "W"
    device_class: power
    min_value: 0
    max_value: 8000
    step: 1
    value_type: U_WORD
    entity_category: config
    mode: box
    disabled_by_default: true
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Hackman Flex3L Generator Peak Shaving Power"
    id: hackman_flex3l_generator_peak_shaving_power
    register_type: holding
    address: 290
    unit_of_measurement: "W"
    device_class: power
    value_type: U_WORD
    min_value: 0
    step: 1
    entity_category: config
    mode: box
    icon: "mdi:generator-stationary"
# --- KONIEC PLIKU GENERATOR ---
