# --- POCZĄTEK PLIKU TOU ---
# Wersja v2.03 - Golden Release (Skalpel na moc).
# Zmiany: Napięcie: Działa idealnie (lambda * 0.1, write_lambda * 10.0). Moc: Zastosowano twarde kompensowanie "ducha z pamięci" poprzez lambdę (lambda * 0.1 przy odczycie 120 000 da nam 12 000, write_lambda * 10 do zapisu, omijając bugi natywnego multiply i wymuszając nadpisanie rejestrów inwertera na poziomie 12000W). Tryb box dla stabilności.

substitutions:
  func_int_to_time: |-
    uint8_t hours = raw / 100;
    uint8_t minutes = raw - (hours * 100);
    return ESPTime {.minute = minutes, .hour = hours};
  func_time_to_int: "return x.hour * 100 + x.minute;"

datetime:
  - platform: template
    name: "Time of Use 1 Start"
    id: hackman_flex3l_time_of_use_1_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_1_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 2 Start"
    id: hackman_flex3l_time_of_use_2_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_2_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 3 Start"
    id: hackman_flex3l_time_of_use_3_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_3_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_3_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 4 Start"
    id: hackman_flex3l_time_of_use_4_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_4_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_4_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 5 Start"
    id: hackman_flex3l_time_of_use_5_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_5_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_5_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 6 Start"
    id: hackman_flex3l_time_of_use_6_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(hackman_flex3l_time_of_use_6_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: hackman_flex3l_time_of_use_6_start_raw
          value: !lambda ${func_time_to_int}

switch:
  - platform: template
    name: "Time of Use"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00000001) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00000001;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00000001;"

  - platform: template
    name: "Time of Use Monday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00000010) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00000010;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00000010;"

  - platform: template
    name: "Time of Use Tuesday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00000100) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00000100;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00000100;"

  - platform: template
    name: "Time of Use Wednesday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00001000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00001000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00001000;"

  - platform: template
    name: "Time of Use Thursday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00010000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00010000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00010000;"

  - platform: template
    name: "Time of Use Friday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b00100000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b00100000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b00100000;"

  - platform: template
    name: "Time of Use Saturday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b01000000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b01000000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b01000000;"

  - platform: template
    name: "Time of Use Sunday"
    icon: "mdi:toggle-switch"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_enabled_raw).state & 0b10000000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state | 0b10000000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_enabled_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_enabled_raw).state & ~0b10000000;"

  - platform: template
    name: "Time of Use 1 Grid Charge"
    id: hackman_flex3l_switch_time_of_use_1_grid_charge
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_1_raw).state & 0b00000001) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state | 0b00000001;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state & ~0b00000001;"

  - platform: template
    name: "Time of Use 1 Gen"
    id: hackman_flex3l_switch_time_of_use_1_gen
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_1_raw).state & 0b00000010) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state | 0b00000010;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state & ~0b00000010;"

  - platform: template
    name: "Time of Use 1 Sell"
    id: hackman_flex3l_switch_time_of_use_1_sell
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    disabled_by_default: true
    lambda: "return ((int)id(hackman_flex3l_time_of_use_1_raw).state & 0b00100000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state | 0b00100000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_1_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_1_raw).state & ~0b00100000;"

  - platform: template
    name: "Time of Use 2 Grid Charge"
    id: hackman_flex3l_switch_time_of_use_2_grid_charge
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_2_raw).state & 0b00000001) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state | 0b00000001;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state & ~0b00000001;"

  - platform: template
    name: "Time of Use 2 Gen"
    id: hackman_flex3l_switch_time_of_use_2_gen
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_2_raw).state & 0b00000010) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state | 0b00000010;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state & ~0b00000010;"

  - platform: template
    name: "Time of Use 2 Sell"
    id: hackman_flex3l_switch_time_of_use_2_sell
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    disabled_by_default: true
    lambda: "return ((int)id(hackman_flex3l_time_of_use_2_raw).state & 0b00100000) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state | 0b00100000;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_of_use_2_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_2_raw).state & ~0b00100000;"

  - platform: template
    name: "Time of Use 3 Grid Charge"
    id: hackman_flex3l_switch_time_of_use_3_grid_charge
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    lambda: "return ((int)id(hackman_flex3l_time_of_use_3_raw).state & 0b00000001) != 0;"
    turn_on_action:
      - number.set:
          id: hackman_flex3l_time_of_use_3_raw
          value: !lambda "return (int)id(hackman_flex3l_time_of_use_3_raw).state | 0b00000001;"
    turn_off_action:
      - number.set:
          id: hackman_flex3l_time_
